import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Tour",
      items: [
        "tour/intro",
        "tour/hello-world",
        "tour/install",
        "tour/containers",
        "tour/connections",
        "tour/shapes",
        "tour/style",
        "tour/text",
        "tour/icons",
        "tour/classes",
        "tour/sql-tables",
        "tour/uml-classes",
        "tour/sequence-diagrams",
        "tour/grid-diagrams",
        "tour/imports",
        "tour/vars",
        "tour/comments",
        "tour/strings",
        "tour/overrides",
        "tour/layers",
        "tour/scenarios",
        "tour/steps",
        "tour/globs",
        "tour/composition",
        "tour/nested-composition",
        "tour/positions",
        "tour/dimensions",
        "tour/linking",
        "tour/themes",
        "tour/fonts",
        "tour/exports",
        "tour/auto-formatter",
        "tour/layouts",
        "tour/dagre",
        "tour/elk",
        "tour/tala",
        "tour/legend",
        "tour/interactive",
        "tour/extensions",
        "tour/api",
        "tour/community",
        "tour/discord",
        "tour/slack",
        "tour/vim",
        "tour/vscode",
        "tour/editor-support",
        "tour/obsidian",
        "tour/confluence",
        "tour/man",
        "tour/help",
        "tour/troubleshoot",
        "tour/cheat-sheet",
        "tour/faq",
        "tour/design",
        "tour/experience",
        "tour/future",
        "tour/studio",
        "tour/sketch",
        "tour/composition-formats",
        "tour/models",
        "tour/model-view",
        "tour/imports-use-cases",
        "tour/modular-classes",
        "tour/version-visualization",
      ],
    },
    {
      type: "category",
      label: "Examples",
      items: [
        "examples/overview",
        "examples/dagre",
        "examples/elk",
        "examples/tala",
      ],
    },
    {
      type: "category",
      label: "Releases",
      items: [
        "releases/intro",
        "releases/0.7.0",
        "releases/0.6.9",
        "releases/0.6.8",
        "releases/0.6.7",
        "releases/0.6.6",
        "releases/0.6.5",
        "releases/0.6.4",
        "releases/0.6.3",
        "releases/0.6.2",
        "releases/0.6.1",
        "releases/0.6.0",
        "releases/0.5.1",
        "releases/0.5.0",
        "releases/0.4.2",
        "releases/0.4.1",
        "releases/0.4.0",
        "releases/0.3.0",
        "releases/0.2.6",
        "releases/0.2.5",
        "releases/0.2.4",
        "releases/0.2.3",
        "releases/0.2.2",
        "releases/0.2.1",
        "releases/0.2.0",
        "releases/0.1.6",
        "releases/0.1.5",
        "releases/0.1.4",
        "releases/0.1.3",
        "releases/0.1.2",
        "releases/0.1.1",
        "releases/0.1.0",
        "releases/0.0.13",
      ],
    },
  ],
};

export default sidebars;