deploy: {
  icon: https://icons.terrastruct.com/aws%2FDeveloper%20Tools%2FAWS-CodeDeploy.svg
}

backup: {
  icon: https://icons.terrastruct.com/aws%2FStorage%2FAWS-Backup.svg
}

deploy -> backup: {
  icon: https://icons.terrastruct.com/infra%2F002-backup.svg
}
