classes: {
  base: {
    style: {
      border-radius: 4
      shadow: true
    }
  }
  error: {
    style.fill: pink
    style.stroke: red
  }
  med: {
    width: 200
    height: 200
    style.font-size: 24
  }
  large: {
    width: 300
    height: 300
    style.font-size: 28
  }
  xlarge: {
    width: 400
    height: 400
    style.font-size: 32
  }
  person: {
    shape: person
    style.stroke-dash: 3
  }
}
