# Shape catalog of standard shapes

style.fill: transparent

grid-rows: 4
grid-columns: 4
rectangle.shape: rectangle
square.shape: square
page.shape: page
parallelogram.shape: parallelogram
document.shape: document
cylinder.shape: cylinder
queue.shape: queue
package.shape: package
step.shape: step
callout.shape: callout
stored_data.shape: stored_data
person.shape: person
diamond.shape: diamond
oval.shape: oval
circle.shape: circle
hexagon.shape: hexagon
cloud.shape: cloud

# Color fixups to ensure all shapes have white fill
# TODO change this to use globs when implemented
parallelogram.style.fill: white
queue.style.fill: white
person.style.fill: white
diamond.style.fill: white
hexagon.style.fill: white
page.style.fill: white
document.style.fill: white
cylinder.style.fill: white
package.style.fill: white
step.style.fill: white
stored_data.style.fill: white
square.style.fill: white
oval.style.fill: white
circle.style.fill: white
rectangle.style.fill: white
