ci-runner
codedeploy: {
  tooltip: |md
    God has abandoned this pipeline
  |
  tooltip.near: center-left
}
aws instance

ci-runner -> codedeploy -> aws instance: safe deploy
ci-runner -> aws instance: direct deploy
