a: |md
  床前明月光，

  疑是地上霜。

  举头望明月，

  低头思故乡。
|

b: "トマトが赤くなったのはなぜですか？\nBecause it saw the salad dressing!👩‍👩‍👧‍👶👩‍👩‍👧‍👶" {
  style.font-size: 55
}

c: ສະບາຍດີ (sabaai dii) - Lao
d: ជំរាបសួរ (jomreab suor) - Khmer {
  style.font-size: 43
}

a -> b -> c
a -> d
