text: |md
  # Introduction

  ## How to start a cult

  This presentation educates the public on starting a cult

  This is an abridged presentation
|

layers: {
  1: {
    text: |md
      # What is a cult?
      - *Definition*: A group or movement with a shared devotion to a charismatic leader, an ideology, or a set of rituals and beliefs
      - *Characteristics*: Totalitarian control, manipulative practices, and exploitation of members
    |
  }
  2: {
    text: |md
      # Charismatic Leader

      ## Role

      Cult leaders have a strong, magnetic personality, and are typically seen as an authority figure

      ## Tips:

      - Cultivate a unique and compelling persona
      - Be convincing and persuasive
      - Establish yourself as an authority figure with exclusive knowledge or abilities
    |
  }
  3: {
    text: |md
      # Recruitment
      - *Importance*: New members are vital for the growth and sustainability of a cult
      - *Methods*: Targeting vulnerable individuals, offering solutions to personal problems, and using social pressure
    |
  }
  4: {
    text: |md
      # Control and manipulation

      ## Purpose
      To maintain power over members and ensure loyalty

      ## Techniques
      Information control, emotional manipulation, and behavior control

      ## Tips:

      - Limit members' access to outside information and discourage critical thinking
      - Use guilt, shame, and fear to manipulate members' emotions
      - Create strict rules and rituals to control behavior
    |
  }
  5: {
    text: |md
      # Enjoy your cult
    |
  }
}
