The shire

journey: {
  link: layers.rivendell
}

layers: {
  rivendell: {
    elves: {
      elrond -> frodo: gives advice
    }

    take me home sam.link: _
    go deeper: {
      link: layers.moria
    }
    
    layers: {
      moria: {
        dwarves

        take me home sam.link: _._
      }
    }
  }
}
